<?php

return [
    'platform-super-admin' => [
        'code' => 'PLATFORM.SUPER.ADMIN',
        'name' => 'System Administrator',
        'description' => 'Ministry of Health ICT. Full platform access across all facilities.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [],
    ],

    'platform-user-admin' => [
        'code' => 'PLATFORM.USER.ADMIN',
        'name' => 'Platform User Administrator',
        'description' => 'Manages user accounts and facility assignments across the platform.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'platform.users.read',
            'platform.users.create',
            'platform.users.update',
            'platform.users.update-status',
            'platform.users.manage-facilities',
            'platform.users.reset-password',
            'platform.users.view-audit-logs',
            'platform.users.approval-cases.read',
            'platform.users.approval-cases.create',
            'platform.users.approval-cases.manage',
            'platform.users.approval-cases.review',
            'platform.users.approval-cases.view-audit-logs',
            'platform.facilities.read',
            'platform.facilities.create',
            'platform.facilities.update',
            'platform.facilities.update-status',
            'platform.facilities.manage-owners',
            'platform.facilities.manage-subscriptions',
            'platform.facilities.view-audit-logs',
        ],
    ],

    'platform-rbac-admin' => [
        'code' => 'PLATFORM.RBAC.ADMIN',
        'name' => 'Platform RBAC Administrator',
        'description' => 'Manages roles, permissions, and access policies across the platform.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'platform.rbac.read',
            'platform.rbac.manage-roles',
            'platform.rbac.manage-user-roles',
            'platform.rbac.view-audit-logs',
            'platform.users.read',
            'platform.users.view-audit-logs',
            'platform.feature-flag-overrides.manage',
            'platform.cross-tenant.view-audit-logs',
            'platform.cross-tenant.view-audit-holds',
            'platform.cross-tenant.manage-audit-holds',
            'platform.cross-tenant.read',
        ],
    ],

    'platform-subscription-admin' => [
        'code' => 'PLATFORM.SUBSCRIPTION.ADMIN',
        'name' => 'Subscription Administrator',
        'description' => 'Manages facility subscriptions, plans, and entitlements.',
        'access_level' => 'manage',
        'scope_type' => 'cross_facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'platform.subscription-plans.read',
            'platform.subscription-plans.manage',
            'platform.subscription-plans.view-audit-logs',
            'platform.facilities.read',
            'platform.facilities.manage-subscriptions',
            'platform.facilities.view-audit-logs',
            'platform.multi-facility.read',
            'platform.multi-facility.manage-rollouts',
            'platform.multi-facility.manage-incidents',
            'platform.multi-facility.execute-rollback',
            'platform.multi-facility.approve-acceptance',
            'platform.multi-facility.view-audit-logs',
        ],
    ],

    'clinical-officer' => [
        'code' => 'CLINICAL.GENERAL',
        'name' => 'Clinical Officer',
        'description' => 'Diploma-level clinician. Main clinical staff at dispensaries and health centres.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: see whether the visit in front of you is cleared.
            'cashier.charges.read',
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'admissions.read',
            'medical.records.read', 'medical.records.create',
            'patient.demographics.update',
            'patient.medications.manage',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'medical.records.amend',
            'medical.records.update-status',
            'medical.records.handoff.accept',
            'medical.records.handoff.cancel',
            'lab.order',
            'medication.prescribe',
            'imaging.order',
            'laboratory.orders.read',
            'pharmacy.orders.read',
            'radiology.orders.read',
            'clinical-procedure.orders.read',
            'clinical-procedure.order',
            // clinician/orders/referral is guarded by this and no physician role
            // held it, so a doctor could not raise a referral (2026-08-16).
            'service.requests.create',
        ],
    ],

    'medical-officer' => [
        'code' => 'CLINICAL.PHYSICIAN',
        'name' => 'Medical Officer',
        'description' => 'Medical degree holder. Works at hospitals and health centres.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: treat now, reconcile later. Deliberately not held by
            // any finance role — the call is clinical.
            'cashier.charges.emergency-override',
            // Cashier Phase 6: see whether the visit in front of you is cleared.
            'cashier.charges.read',
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'admissions.read', 'admissions.create',
            'medical.records.read', 'medical.records.create',
            'patient.demographics.update',
            'patient.allergies.manage',
            'patient.medications.manage',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'medical.records.amend',
            'medical.records.update-status',
            'medical.records.handoff.accept',
            'medical.records.handoff.cancel',
            'medical.records.attest',
            'lab.order',
            'medication.prescribe',
            'imaging.order',
            'admissions.update-status',
            'laboratory.orders.read',
            'pharmacy.orders.read',
            'radiology.orders.read',
            'clinical-procedure.orders.read',
            'clinical-procedure.order',
            // clinician/orders/referral is guarded by this and no physician role
            // held it, so a doctor could not raise a referral (2026-08-16).
            'service.requests.create',
        ],
    ],

    'surgeon' => [
        'code' => 'CLINICAL.SURGEON',
        'name' => 'Surgeon',
        'description' => 'Surgical specialist. Performs operations and post-op care.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: see whether the visit in front of you is cleared.
            'cashier.charges.read',
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'admissions.read', 'admissions.create',
            'medical.records.read', 'medical.records.create',
            'patient.demographics.update',
            'patient.allergies.manage',
            'patient.medications.manage',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'medical.records.amend',
            'medical.records.update-status',
            'medical.records.handoff.accept',
            'medical.records.handoff.cancel',
            'lab.order',
            'medication.prescribe',
            'imaging.order',
            'theatre.procedures.read',
            'theatre.procedures.create',
            'theatre.procedures.update-status',
            'laboratory.orders.read',
            'pharmacy.orders.read',
            'radiology.orders.read',
            'clinical-procedure.orders.read',
            'clinical-procedure.order',
            // clinician/orders/referral is guarded by this and no physician role
            // held it, so a doctor could not raise a referral (2026-08-16).
            'service.requests.create',
        ],
    ],

    'nurse-officer' => [
        'code' => 'CLINICAL.NURSE',
        'name' => 'Nurse Officer',
        'description' => 'Registered Nurse. Provides bedside care, medication administration, patient monitoring.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: see whether the visit in front of you is cleared.
            'cashier.charges.read',
            'patients.read',
            'appointments.read',
            'admissions.read',
            'medical.records.read',
            'inpatient.ward.read',
            'inpatient.ward.create-task',
            'inpatient.ward.update-task-status',
            'inpatient.ward.create-care-plan',
            'inpatient.ward.update-care-plan',
            'inpatient.ward.create-round-note',
            'patient.vitals.record',
            'lab.sample.collect',
            'service.requests.create',
            'service.requests.read',
            'clinical-procedure.orders.read',
            'clinical-procedure.order',
            'clinical-procedure.perform',
            'clinical-procedure.orders.update-status',
            'clinical-procedure.orders.view-audit-logs',
            // nursing/notes/{id} is guarded by this. CLINICAL.NURSE.MIDWIFE
            // already held it for the same nursing notes — the plain nurse role
            // simply never did (2026-08-16).
            'medical.records.create',
            // Outpatient triage: claiming a patient, recording the handoff,
            // releasing the claim. Previously gated behind emergency.triage.*
            // (CLINICAL.EMERGENCY only), so a nurse got a 403 claiming triage
            // and the "In Triage" state was unreachable (2026-08-16).
            'appointments.record-triage',
            // The MAR is the instrument this role's workspace is built around,
            // yet the role could not read it: GET /nursing/mar is guarded by
            // pharmacy.orders.read, which was granted to physicians, surgeons
            // and pharmacy staff but not to nurses. The nursing workspace
            // therefore 403'd on mount for every nurse (2026-08-16 RBAC audit).
            'pharmacy.orders.read',
        ],
    ],

    'nurse-midwife' => [
        'code' => 'CLINICAL.NURSE.MIDWIFE',
        'name' => 'Nurse Midwife',
        'description' => 'Specialised in maternal and child health. Antenatal, delivery, postnatal care.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: see whether the visit in front of you is cleared.
            'cashier.charges.read',
            'patients.read', 'patients.create',
            'appointments.read', 'appointments.create',
            'medical.records.read', 'medical.records.create',
            'patient.demographics.update',
            'patient.vitals.record',
            'medical.records.draft.update',
            'medical.records.finalize',
            'lab.sample.collect',
            // Midwives run RCH triage for the same reason nurses run OPD triage.
            'appointments.record-triage',
        ],
    ],

    'lab-technologist' => [
        'code' => 'LAB.STAFF',
        'name' => 'Laboratory Technologist',
        'description' => 'Performs lab tests, enters results. Cannot order tests.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'laboratory.access',
            'laboratory.orders.read',
            'lab.sample.collect',
            'lab.sample.reject',
            'lab.test.perform',
            'lab.result.enter',
        ],
    ],

    'lab-supervisor' => [
        'code' => 'LAB.SUPERVISOR',
        'name' => 'Chief Laboratory Technologist',
        'description' => 'Supervises lab staff. Verifies and releases results.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'laboratory.access',
            'laboratory.orders.read',
            'lab.sample.collect',
            'lab.sample.reject',
            'lab.test.perform',
            'lab.result.enter',
            'lab.result.verify',
            'lab.result.release',
            'laboratory.orders.audit-logs.view',
        ],
    ],

    'lab-manager' => [
        'code' => 'LAB.MANAGER',
        'name' => 'Laboratory Manager',
        'description' => 'Manages laboratory operations, quality control, and staffing.',
        'access_level' => 'manage',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'laboratory.access',
            'laboratory.orders.read',
            'lab.sample.collect',
            'lab.sample.reject',
            'lab.test.perform',
            'lab.result.enter',
            'lab.result.verify',
            'lab.result.release',
            'laboratory.orders.audit-logs.view',
        ],
    ],

    'dispenser' => [
        'code' => 'PHARMACY.STAFF',
        'name' => 'Dispenser',
        'description' => 'Diploma pharmaceutical technician. Dispenses medications under supervision.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'pharmacy.access',
            'pharmacy.orders.read',
            'medication.dispense',
        ],
    ],

    'pharmacist' => [
        'code' => 'PHARMACY.SUPERVISOR',
        'name' => 'Pharmacist-in-Charge',
        'description' => 'Degree pharmacist. Verifies prescriptions, manages pharmacy.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'pharmacy.access',
            'pharmacy.orders.read',
            'pharmacy.orders.verify-dispense',
            'pharmacy.orders.manage-policy',
            'pharmacy.orders.reconcile',
            'medication.dispense',
            'dispense.cancel',
            'pharmacy.orders.audit-logs.view',
        ],
    ],

    'radiographer' => [
        'code' => 'RADIOLOGY.STAFF',
        'name' => 'Radiographer',
        'description' => 'Performs X-ray and imaging procedures.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'imaging.access',
            // Without this a radiographer cannot list, open or count the very
            // worklist their workspace is built on — every read route is
            // guarded by it, so the screen would 403 on mount. Only clinicians
            // held it, which was survivable while radiology had no workspace of
            // its own. LAB.STAFF carries the matching `laboratory.orders.read`.
            'radiology.orders.read',
            'imaging.order',
            'imaging.perform',
            'imaging.result.enter',
        ],
    ],

    'radiographer-senior' => [
        'code' => 'RADIOLOGY.SUPERVISOR',
        'name' => 'Senior Radiographer',
        'description' => 'Supervises radiology staff. Verifies imaging reports.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'imaging.access',
            'radiology.orders.read',
            'imaging.order',
            'imaging.perform',
            'imaging.result.enter',
            'imaging.result.verify',
            'radiology.orders.audit-logs.view',
        ],
    ],

    'cashier' => [
        'code' => 'FINANCE.CASHIER',
        'name' => 'Cashier',
        'description' => 'Receives payments, issues receipts, manages daily cash.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: operate the counter. Deliberately holds no approval
            // permission — every second-person control belongs to a supervisor,
            // and a cashier who could clear their own variance is not a control.
            'cashier.access',
            'cashier.charges.read',
            'cashier.charges.create',
            'cashier.charges.cancel',
            'cashier.payments.record',
            'cashier.payments.read',
            'cashier.payments.reverse',
            'cashier.receipts.read',
            'cashier.receipts.reprint',
            'cashier.sessions.read',
            'cashier.sessions.open',
            'cashier.sessions.close',
            'cashier.sessions.move-cash',
            'cashier.refunds.request',
            'patients.read',
        ],
    ],

    'receptionist' => [
        'code' => 'ADMIN.REGISTRATION',
        'name' => 'Health Records Officer',
        'description' => 'Manages patient registration, appointments, front desk.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: the desk needs to see the prepaid gate it enforces.
            'cashier.charges.read',
            'patients.read', 'patients.create',
            'patient.demographics.update',
            'appointments.read', 'appointments.create',
            'appointment.reschedule', 'appointment.cancel',
            'appointment.check-in',
            'service.requests.create',
            'service.requests.read',
            // The registration form collects insurance and posts it immediately,
            // but this role could not write it — the POST 403'd and the UI fell
            // back to "Patient registered, but insurance record could not be
            // saved." Held only by FINANCE.CLAIMS before (2026-08-16).
            'patients.insurance.manage',
            'patients.insurance.verify',
            // Reception routes patients to a clinician at triage handoff, so it
            // needs the clinical directory GET /reception/clinicians serves.
            // That route is guarded by staff.clinical-directory.read, which
            // this role did not hold — so the reception workspace 403'd on
            // mount (2026-08-16 RBAC audit).
            'staff.clinical-directory.read',
        ],
    ],

    'hospital-admin' => [
        'code' => 'ADMIN.FACILITY',
        'name' => 'Hospital Administrator',
        'description' => 'Manages facility operations, staffing, and administration.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: treat now, reconcile later. Deliberately not held by
            // any finance role — the call is clinical.
            'cashier.charges.emergency-override',
            'patients.read', 'patients.create', 'patient.demographics.update',
            'patients.update-status',
            'appointments.read', 'appointments.create', 'appointment.reschedule',
            'medical.records.read', 'medical.records.archive', 'medical.records.audit-logs.view',
            'admissions.read', 'admissions.create', 'admissions.update',
            'laboratory.access', 'pharmacy.access', 'imaging.access',
            'staff.read', 'staff.create',
            'staff.employment.update', 'staff.status.update',
            'staff.documents.read', 'staff.documents.create',
            'staff.documents.verify',
            'staff.credentialing.read', 'staff.credentialing.verify',
            'staff.attendance.read', 'staff.attendance.update',
            'departments.read', 'departments.create', 'departments.update',
            'platform.clinical-catalog.read',
            'platform.clinical-catalog.manage-clinical-procedures',
            'platform.resources.read',
            'platform.resources.manage-ward-beds',
            'platform.resources.manage-observation-rooms',
            'inventory.procurement.read',
            'clinical-procedure.orders.read',
            'clinical-procedure.orders.view-audit-logs',
        ],
    ],

    'nutritionist' => [
        'code' => 'ALLIED.NUTRITIONIST',
        'name' => 'Nutritionist',
        'description' => 'Manages therapeutic feeding, malnutrition, and dietary counseling.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'medical.records.read',
            'medical.records.create',
            'medical.records.draft.update',
        ],
    ],

    'counselor' => [
        'code' => 'ALLIED.COUNSELOR',
        'name' => 'Counselor',
        'description' => 'Provides HIV testing counseling, adherence support, psychosocial support.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'medical.records.read',
            'medical.records.create',
            'medical.records.draft.update',
        ],
    ],

    'community-health-worker' => [
        'code' => 'ALLIED.COMMUNITY.HEALTH.WORKER',
        'name' => 'Community Health Worker',
        'description' => 'Conducts home visits, defaulter tracing, health education, and outreach.',
        'access_level' => 'view',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'patients.create',
            'appointments.read',
        ],
    ],

    'medical-attendant' => [
        'code' => 'SUPPORT.MEDICAL.ATTENDANT',
        'name' => 'Medical Attendant',
        'description' => 'Patient hygiene, bed-making, linen, cleaning, basic patient care.',
        'access_level' => 'view',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inpatient.ward.read',
            'inpatient.ward.create-task',
            'inpatient.ward.update-task-status',
        ],
    ],

    'health-secretary' => [
        'code' => 'SUPPORT.HEALTH.SECRETARY',
        'name' => 'Health Secretary',
        'description' => 'Front desk, document management, appointment scheduling, referrals.',
        'access_level' => 'view',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'appointments.read', 'appointments.create',
            'service.requests.create',
            'service.requests.read',
        ],
    ],

    'dental-officer' => [
        'code' => 'CLINICAL.DENTAL.OFFICER',
        'name' => 'Dental Officer',
        'description' => 'Dental exams, extractions, fillings, oral health education.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: see whether the visit in front of you is cleared.
            'cashier.charges.read',
            'patients.read',
            'appointments.read', 'appointments.create',
            'medical.records.read', 'medical.records.create',
            'patient.demographics.update',
            'medical.records.draft.update',
            'medical.records.finalize',
        ],
    ],

    'emergency-nurse' => [
        'code' => 'CLINICAL.EMERGENCY',
        'name' => 'Casualty Nurse',
        'description' => 'Emergency and casualty care, triage, acute patient management.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: treat now, reconcile later. Deliberately not held by
            // any finance role — the call is clinical.
            'cashier.charges.emergency-override',
            // Cashier Phase 6: see whether the visit in front of you is cleared.
            'cashier.charges.read',
            'patients.read',
            'appointments.read',
            'admissions.read',
            'medical.records.read',
            'emergency.triage.create',
            'emergency.triage.update',
            'emergency.triage.update-status',
            'emergency.triage.read',
            'patient.vitals.record',
            'lab.sample.collect',
        ],
    ],

    'accountant' => [
        'code' => 'FINANCE.OFFICER',
        'name' => 'Accountant',
        'description' => 'Handles accounts, reconciliations, financial reporting.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: reads the books, handles no cash.
            'cashier.access',
            'cashier.charges.read',
            'cashier.payments.read',
            'cashier.receipts.read',
            'cashier.sessions.read',
            'cashier.reports.read',
            'patients.read',
        ],
    ],

    'finance-manager' => [
        'code' => 'FINANCE.CONTROLLER',
        'name' => 'Finance Manager',
        'description' => 'Oversees financial operations, approvals, audits.',
        'access_level' => 'manage',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            // Cashier Phase 6: the approve column. Also allowed to work a till when
            // short-staffed, so the use cases enforce requester != approver
            // rather than trusting this split on its own.
            'cashier.access',
            'cashier.charges.read',
            'cashier.charges.create',
            'cashier.charges.cancel',
            'cashier.payments.record',
            'cashier.payments.read',
            'cashier.payments.reverse',
            'cashier.receipts.read',
            'cashier.receipts.reprint',
            'cashier.sessions.read',
            'cashier.sessions.open',
            'cashier.sessions.close',
            'cashier.sessions.move-cash',
            'cashier.sessions.approve-variance',
            'cashier.refunds.request',
            'cashier.refunds.approve',
            'cashier.waivers.approve',
            'cashier.reports.read',
            'patients.read',
        ],
    ],

    'insurance-officer' => [
        'code' => 'FINANCE.CLAIMS',
        'name' => 'Insurance Claims Officer',
        'description' => 'Processes insurance claims, verifications, and reconciliations.',
        'access_level' => 'request',
        'scope_type' => 'facility',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'patients.read',
            'patients.insurance.read',
            'patients.insurance.manage',
            'patients.insurance.verify',
        ],
    ],

    'storekeeper' => [
        'code' => 'INVENTORY.STAFF',
        'name' => 'Storekeeper',
        'description' => 'Manages stock, inventory movements, and warehouse operations.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inventory.view-own-items',
            'inventory.view-requisition-own',
            'inventory.view-warehouse-own-department',
            'inventory.create-requisition-own-department',
        ],
    ],

    'senior-storekeeper' => [
        'code' => 'INVENTORY.SUPERVISOR',
        'name' => 'Senior Storekeeper',
        'description' => 'Supervises store operations, approves requisitions.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inventory.view-own-items',
            'inventory.view-department-items',
            'inventory.view-requisition-own',
            'inventory.view-warehouse-own-department',
            'inventory.create-requisition-own-department',
            'inventory.approve-requisition-own-department',
            'inventory.execute-warehouse-transfer-own-department',
        ],
    ],

    'procurement-officer' => [
        'code' => 'INVENTORY.MANAGER',
        'name' => 'Procurement Officer',
        'description' => 'Manages procurement, supplier relationships, and budget controls.',
        'access_level' => 'manage',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'inventory.view-own-items',
            'inventory.view-department-items',
            'inventory.view-requisition-own',
            'inventory.view-warehouse-own-department',
            'inventory.create-requisition-own-department',
            'inventory.create-requisition-cross-department',
            'inventory.approve-requisition-own-department',
            'inventory.manage-warehouse-own-department',
            'inventory.execute-warehouse-transfer-own-department',
            'inventory.authorize-warehouse-transfer-receiving-department',
            'inventory.dispose-items-own-department',
            'inventory.procurement.read',
            'inventory.procurement.correct-movement',
            'inventory.procurement.manage-item-units',
            'inventory.procurement.manage-unit-prices',
            'inventory.procurement.set-opening-stock',
        ],
    ],

    'theatre-nurse' => [
        'code' => 'THEATRE.STAFF',
        'name' => 'Theatre Nurse',
        'description' => 'Assists in surgical procedures, manages theatre resources.',
        'access_level' => 'request',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'theatre.procedures.read',
            'theatre.procedures.create',
        ],
    ],

    'theatre-nurse-in-charge' => [
        'code' => 'THEATRE.SUPERVISOR',
        'name' => 'Theatre Nurse-in-Charge',
        'description' => 'Supervises theatre operations, schedules procedures.',
        'access_level' => 'approve',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'theatre.procedures.read',
            'theatre.procedures.create',
            'theatre.procedures.update',
            'theatre.procedures.update-status',
            'theatre.procedures.manage-resources',
        ],
    ],

    'theatre-manager' => [
        'code' => 'THEATRE.MANAGER',
        'name' => 'Theatre Manager',
        'description' => 'Manages theatre department, resource planning, and quality.',
        'access_level' => 'manage',
        'scope_type' => 'own_department',
        'is_system' => true,
        'status' => 'active',
        'permissions' => [
            'theatre.procedures.read',
            'theatre.procedures.create',
            'theatre.procedures.update',
            'theatre.procedures.update-status',
            'theatre.procedures.manage-resources',
            'theatre.procedures.view-resource-audit-logs',
        ],
    ],
];
