<?php

namespace App\Modules\Revenue\Presentation\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RecordCashPaymentRequest extends FormRequest
{
    /**
     * Authorization is the route's `can:` middleware; this validates shape only.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'patientId' => ['required', 'uuid'],
            'serviceChargeIds' => ['required', 'array', 'min:1'],
            'serviceChargeIds.*' => ['required', 'uuid', 'distinct'],
            // Minor units, as an integer. Accepting a decimal here would put a
            // float on the wire and hand the rounding decision to the client.
            'tenderedAmountMinor' => ['required', 'integer', 'min:0'],
            // Generated by the client when the payment dialog opens, not on
            // submit — that is what makes a double-tap idempotent rather than
            // producing two keys for one intent.
            'idempotencyKey' => ['required', 'string', 'max:100'],
            'cashierSessionId' => ['nullable', 'uuid'],
        ];
    }
}
